spring.application.name=Student-app

# Database Connection
spring.datasource.url=jdbc:postgresql://postgres:5432/mydb
spring.datasource.username=jagat
spring.datasource.password=1111

# JPA / Hibernate Lifecycle Setup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# This forces Hibernate to run 'update' BEFORE data.sql executes
spring.jpa.defer-datasource-initialization=true

# Database Script Control
spring.sql.init.mode=always
spring.sql.init.platform=postgres

# H2 Console (Optional - can be removed if strictly using PostgreSQL)
spring.h2.console.enabled=true

# Example for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

